logging:
  level:
    io:
      craft:
        giftcard: INFO
spring:
  application:
    name: Giftcard
  jackson:
    default-property-inclusion: non_absent
  profiles:
    active: '@spring.profiles.active@'
server:
  port: 8080
springdoc:
  enable-native-support: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true
