== Design de l'agrégat

[.notes]
--
Qui dit nouveau projet dit choix d'architecture, et surtout concernant la gestion de l'agrégat.

là on a plusieurs possibilités, je vais n'en citer que deux heeuu parce que.

*click*
--

=== State sourcing

[.notes]
--
Le State sourcing, c'est la manière de gérer nos agrégats comme on fait d'habitude.

Sans parler d'objets dits "anémiques", on va quand même, pour une requête donnée,
mettre à jour l'état de l'agrégat, soit le muter, soit en faire une copie.

C'est-à-dire qu'après un changement, on se retrouve avec la dernière version dans les mains.

Je vais prendre un exemple pour illustrer le truc

Imaginons vous avez...au hasard... des cartes cadeaux à gérer
--

[%notitle]
=== example statefull

[cols="4*",options="header"]
|=============================================================
| barcode | shopping +
                      store | remaning +
                                        amount  |  exhausted()
| 1234    | Restaurant      | 90 €              |    false
|=============================================================

[.notes]
--
Alors ça ressemble vachement à une table sql mais on parle bien d'un agrégat ici.
Même si ça arrive souvent tel quel en base de données.

Bref quand je déclare ma carte cadeau, j'ai ça en mains,
il y a un code-barre "1234", une boutique "restaurant", un montant "90 €" et une méthode qui nous dit si oui ou non la carte est vie.

Si je paye 30 € avec, j'obtiens ça
--

[%notitle]
=== example statefull

[cols="4*", options="header"]
|=============================================================
| barcode | shopping +
                      store | remaning +
                                        amount  |  exhausted()
| 1234    | Restaurant    | 60 €                |    false
|=============================================================

[.notes]
--
Ma carte cadeau n'a plus que 60 €.

Remarquez que je n'ai plus ici le montant initial.

Et si je dépense les 60 € restants
--

[%notitle]
=== example statefull

[cols="4*", options="header"]
|=============================================================
| barcode | shopping +
                      store | remaning +
                                        amount  |  exhausted()
| 1234    | Restaurant    | 0 €                 |    true
|=============================================================

[.notes]
--
ma carte cadeaux est vide et donc inutilisable.

Mais le point ici c'est que le champ "montant" a été écrasé.

Ce qui veut dire qu'après un changement,
on a certes des valeurs à jour, mais plus aucune trace de ce qu'elles ont été.

Comme je l'ai dit, ça, c'est le fonctionnement classique de nos app.
--

=== Avantages

[%step]
- Facile à comprendre
- Facile à lire
- On fait tout le temps comme ça

[.notes]
--
Regardons les avantages.

*click*

- C'est facile à comprendre, on a un état et on le modifie
- C'est facile à lire, que ce soit en base ou en debug, on voit l'état au premier coup d'œil
- On fait tout le temps comme ça, c'est la manière dont on a appris à faire
--

=== Inconvénients


[%step]
- Perte d'information
- Pas de traçabilité
- Obligation d'anticiper les besoins futurs

[.notes]
--
Par contre côté inconvénients, on a en top #1 la perte d'information.

et les autres qui en découlent, comme par exemple

pas de traçabilité, on sait où on en est mais on n'a aucune idée de comment on y est arrivé.

et on est obligé d'anticiper les besoins futurs,
si demain on veut savoir combien de fois j'ai utilisé ma carte cadeau, c'est mort.
Il faut soit le prévoir dès le début, soit s'asseoir sur les données.

--

=== Event sourcing

[.notes]
--
L'autre choix de gestion de l'agrégat, c'est l'event sourcing.

Là c'est un changement de paradigme.

Plutôt que de stocker l'état de l'agrégat, on va stocker les événements qui ont modifié cet état.

Le premier événement est le début de l'histoire de l'agrégat,
celui qui pose les bases, comme l'identifiant de l'agrégat.

Et on va stacker dans une liste la suite des autres événements de l'histoire.

J'appelle ça l'histoire, mais vous pouvez trouver d'autres noms comme "stream".

Si je reprends mon exemple de carte cadeau,
--


[%notitle.moresmaller]
=== example event sourcing

[cols="4*", options="header"]
|================================================================================================
| type                   | barcode | sequenceId | payload
| GiftCardDeclared       | 1234    | 0          | shoppingStore: "Restaurant", +
                                                   initialAmount: "90 €"
|================================================================================================


[.notes]
--
Lors de ma déclaration de carte carte cadeau,
je crée mon début d'histoire avec l'événement de type "GiftCardDeclared".

Cet événement porte l'identifiant, pour nous c'est le code-barre

Il porte aussi une charge utile, pour nous, c'est le magasin et le montant initial
(les trucs qu'on a tapé dans le formulaire de declaration)

Et si je dis à mon système "je paye 30 € avec"
--

[%notitle.moresmaller]
=== example event sourcing

[cols="4*", options="header"]
|================================================================================================
| type                     | barcode | sequenceId | payload
| GiftCardDeclared         | 1234    | 0          | shoppingStore: "Restaurant", +
                                                     initialAmount: "90 €"
| PaidAmount               | 1234    | 1          | amount: "30 €", +
                                                     on: "2025-03-01"
|================================================================================================


[.notes]
--
boum, j'ai un nouvel événement avec un type différent.

Remarquez que les événements sont des choses qui se sont passées, c'est pour ça qu'on écrit leur type au passé

- la carte a été créée
- un montant a été payé

Il porte lui aussi l'id de l'agrégat, le code-barre et il a pour charge utile le montant qui vient d'être payé
et la date du paiement.

Et je n'ai pas parlé de ce que j'ai appelé sequenceId, c'est une information purement technique
mais qui a son importance, il permet de garantir l'ordre des événements,
et donc d'être sûr qu'on raconte l'histoire dans le bon ordre.

Le début de l'histoire étant zero.

Avançons et payons les 90 - 30 .. 60 € qu'il reste sur la carte
--

[%notitle.moresmaller]
=== example event sourcing

[cols="4*", options="header"]
|================================================================================================
| type                    | barcode | sequenceId | payload
| GiftCardDeclared        | 1234    | 0          | shoppingStore: "Restaurant", +
                                                    initialAmount: "90 €"
| PaidAmount              | 1234    | 1          | amount: "30 €", +
                                                    on: "2025-03-01"
| PaidAmount              | 1234    | 2          | amount: "60 €", +
                                                    on: "2025-03-10"
| GiftCardExhausted       | 1234    | 3          | _null_
|================================================================================================
[.notes]
--
J'ai maintenant 2 nouveaux événements,
un autre paidAmount avec son montant et sa date
et un événement "GiftCardExhausted" qui n'a pas besoin de charge utile.

On pourrait se dire "il peut porter la date", mais dans notre cas un GiftCardExhausted ne vient pas tout seul
il vient avec un événement PaidAmout.

En vrai c'est un choix qu'on a fait, on aurait pu se passer de l'événement GiftCardExhausted
ou bien se passer du PaidAmount et faire porter à l'GiftCardExhausted la date et le montant payé,
voire même juste la date, vu que ça représente la carte vide, elle se retrouverait a 0 de toute manière.

'fin il n'y a pas de recette miracle, l'essentiel c'est de faire des événements qui nous parlent
et qui ont un sens métier.

Voilà, vous avez devant vous une histoire qui est racontée par les changements qui ont été appliqués.
C'est un peu la définition première de l'event sourcing.
--

=== Partons là dessus

[.notes]
--
En vrai on est là pour ça alors je vais vous montrer comment on l'a implémenté.
--
