== Code
🔍

Les événements
[.notes]
--
En attendant, regardons à quoi ça ressemble dans le code
--

=== Interface GiftCardEvent

[source, java, highlight]
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/GiftCardEvent.java[lines='7..']
----

[.notes]
--
Côté événements, pour les manipuler on va créer une interface scellée sobrement appeler GiftCardEvent.

Elle contient des données qui pourraient être considérées comme "technique",
bouh c'est pas beau ça n'a rien à faire dans le domaine.
Mais hé, pas besoin d'être dogmatique si ça permet de simplifier la comprehension du code.
--

=== GiftCardCreated

[source, java, highlight="..|3,5..6"]
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/GiftCardCreated.java[lines='9..']
----

[.notes]
--
Dans les implem, on a le début de notre histoire avec l'événement GiftCardCreated.

*click*

Comme je l'ai dit précédement c'est le début de l'histoire,
il porte l'id de l'agrégat et les données de bases.

ici le montant & le magasin
--

=== PaidAmount

[source, java, highlight='..|5..6']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/PaidAmount.java[lines='9..']
----

[.notes]
--
On en a 3 on va tous les faire, voici le PaidAmount

*click*

Vous vous en souvenez, il porte le montant payé et la date de paiement
--

=== GifCardExhausted

[.smaller]
[source, java, highlight='..']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/GifCardExhausted.java[lines='7,8']
----

[.notes]
--
Notre dernier événement est GifCardExhausted qui se suffit à lui même.
--

=== Code
🔍

L'agrégat

[.notes]
--
Maintenant qu'on a vu les événements, voyons comment on les utilise dans notre agregat.
--

=== `GiftCard.declare()`

[source, java, highlight]
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='14..16, 23']
    // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='25..26']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='27..35']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[tags='closingBrace']
----

[.notes]
--
Tout d'abord, on a la fonction statique `declare` qui va créer notre carte cadeau.

Elle est statique car vu que GiftCardCreated est le début de l'histoire,
on ne peut pas avoir une instance construite avant de décider de commencer l'histoire 🤷

Elle va retourner simplement notre événement GiftCardCreated.
--

[transition="slide-in fade-out"]
=== `giftCard.pay()`

[source, java, highlight='..|12,13|10,11|16|..']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='14..16, 23']
    // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='25..26']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='36, 41..46, 55..57']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[tags='closingBrace']
----

[.notes]
--
Un poil plus compliqué, on a la fonction pay qui va, dans un premier temps,
nous retourner un événement PaidAmount

*click*

On fabrique l'evénement avec notre charge utile venant du command object, le paramètre

*click*

Remarquez que les informations "techniques" viennent directement de l'instance de l'agrégat lui même.

*click*

on le retourne sous forme de liste.

*click*

et pourquoi une liste me direz-vous ?
--

[transition="fade-in slide-out"]
=== `giftCard.pay()`

[source, java, highlight='13..18']
----

include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='14..16, 23']
    // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='25..26']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='36,41']
      // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='46, 48..57']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[tags='closingBrace']
----

[.notes]
--
Parce que si la carte est vide, on a dit qu'on retournait aussi l'événement GifCardExhausted.
--


=== Code
🔍

L'application service

[.notes]
--
On a vu les évents, on a vu leur génération.
C'est joli, mais on a fait un agrégat sans aucun effet de bord.
(Pour info ça s'appelle du Functionnal core)

Maintenant voyons comment on interface notre agrégat avec le reste du monde
grace à notre application service
--

=== `GiftCardApplicationService.declare()`

[source, java, highlight='..|9|10|11']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[lines='17..18,20,23,40..42,48..52']
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[tags='closingBrace']
----

[.notes]
--
voilà, pour la déclaration c'est aussi simple que ça.

*click*

On appelle l'agrégat pour nous fournir l'événement d'init,

*click*

on le sauvegarde

*click*

et on le propage.
--

=== `GiftCardApplicationService.pay()`

[source, java, highlight='..|8|9..11|..']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[lines='17..18,20,23,53..60']
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[tags='closingBrace']
----

[.notes]
--
Côté paiement, c'est tout aussi simple,

*click*

à la différence près qu'on a besoin de fabriquer notre GiftCard depuis son historique.
Qu'on récupère directement depuis l'event store.

*click*

et rebelotte, on demande à l'agrégat de nous fournir des événements pour cette commande, on les sauvegarde et on les propage.

*click*

Pourquoi les propager me direz-vous ?

Pour répondre à ça, j'ai une question pour vous:

Sachant que jusqu'ici, on a manipulé uniquement des événements,

Comment est-ce qu'on affiche la liste des cartes  cadeaux ?

ce dispatcher va nous y aider mais je laisse à Aurélien le soin de vous expliquer d'où ça vient.
--
