== Code
🔍

-> Les événements

L'agrégat

L'application service
[.notes]
--
Pour ça, on va se promener dans le code

En commençant par voir à quoi ressemble un événement,
comment il est produit dans l'agrégat.

Et comment ça s'articule dans un service classique.
--

=== Interface `GiftCardEvent`

[source, java, highlight]
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/GiftCardEvent.java[lines='8..15']
----

[.notes]
--
Côté événements, pour les manipuler on va créer une interface scellée sobrement appeler GiftCardEvent.

Elle force l'implémentation les données communes comme le codebarre, qui est l'identifiant de notre agrégat,
et le séquence Id, le truc dont j'ai parlé tout à l'heure qui force l'histoire dans le bon sens.

On pourrait y rajouter un auteur, une date de création…
--

=== `GiftCardDeclared`

[source, java, highlight="..|3,5..6"]
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/GiftCardDeclared.java[lines='9..']
----

[.notes]
--
Dans les implem, on a le début de notre histoire avec l'événement `GiftCardDeclared`.

*click*

Comme je l'ai dit précédement c'est le début de l'histoire,
il porte l'id de l'agrégat et les données de bases.

ici le montant & le magasin
--

=== `PaidAmount`

[source, java, highlight='..|5..6']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/PaidAmount.java[lines='10..17']
----

[.notes]
--
On a 3 événements, on va tous les faire ça va être rapide, voici le `PaidAmount`

*click*

Vous vous en souvenez, il porte le montant payé et la date de paiement
--

=== `GifCardExhausted`

[.smaller]
[source, java, highlight='..']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/events/GifCardExhausted.java[lines='7,8']
----

[.notes]
--
Pour finir, le dernier événement est `GifCardExhausted` qui se suffit à lui même.
--

=== Code
🔍

Les événements

-> L'agrégat

L'application service

[.notes]
--
Maintenant qu'on a vu les événements, voyons comment on les génère depuis notre agrégat,
le coeur de notre métier.

Il s'appelle d'ailleurs GiftCard
--

=== `GiftCard.declare()`

[source, java, highlight='..|8|9..14']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..12,19']
    // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='21..22']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='23..30']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[tags='closingBrace']
----

[.notes]
--
Tout d'abord, on a la static factory `declare` qui va créer notre carte cadeau.

Elle est statique car on a vu que l'événement GiftCardDeclared était le début de l'histoire.
Si on n'a pas le début de l'histoire, comment est-ce qu'on aurait une instance de quoi que ce soit ? 🤷

*click*

Elle prend en paramètre un GiftCardDeclaration qui est le command object, c'est le détail de ma commande

*click*

Elle va retourner simplement notre événement GiftCardDeclared.
--

[transition="slide-in fade-out"]
=== `giftCard.pay()`

[source, java, highlight='..|12,13|10,11|16|..']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..12,19']
    // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='21..22']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='32, 37..42, 51..53']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[tags='closingBrace']
----

[.notes]
--
Un poil plus compliqué, on a la fonction pay qui va, dans un premier temps,
nous retourner un événement PaidAmount

*click*

On fabrique l'evénement avec notre charge utile venant du command object, le paramètre

*click*

Remarquez que les informations "techniques" viennent directement de l'instance de l'agrégat lui même.

*click*

on le retourne sous forme de liste.

*click*

*Aurélien >* Psourquoi une liste ?
--

[transition="fade-in slide-out"]
=== `giftCard.pay()`

[source, java, highlight='13..18']
----

include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..12,19']
    // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='21..22']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='32,37']
      // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='42, 44..53']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[tags='closingBrace']
----

[.notes]
--
Parce que si la carte est vide, on a dit qu'on retournait aussi l'événement GifCardExhausted.
--


=== Code
🔍

Les événements

L'agrégat

-> L'application service

[.notes]
--
On a vu les évents, on a vu leur génération.
C'est joli, mais on a fait un agrégat sans aucun effet de bord.
(Pour info ça s'appelle du Functional core)

Maintenant voyons comment on interface notre agrégat avec le reste du monde
grace à notre application service qui est notre point d’entrée qui sera appelé par les contrôleurs
--

=== `GiftCardApplicationService.declare()`

[source, java, highlight='..|9|10|11']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[lines='24..25,27,30,47..49,55..59']
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[tags='closingBrace']
----

[.notes]
--
voilà, pour la déclaration c'est aussi simple que ça.

*click*

On appelle l'agrégat pour nous fournir l'événement d'init,

*click*

on le sauvegarde

*click*

et on le propage.
--

=== `GiftCardApplicationService.pay()`

[source, java, highlight='..|8|9..11|..']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[lines='24..25,27,30,60..67']
include::../../../src/main/java/io/craft/giftcard/giftcard/application/GiftCardApplicationService.java[tags='closingBrace']
----

[.notes]
--
Côté paiement, c'est tout aussi simple,

*click*

à la différence près qu'on va agir sur une instance de GiftCard qu'on fabrique depuis son historique.
Qu'on récupère directement depuis l'event store.

*click*

et rebelotte, on demande à l'agrégat de nous fournir des événements pour cette commande, on les sauvegarde et on les propage.

*click*

Pourquoi les propager ?

Pour répondre à ça, j'ai une question pour vous:

Sachant que jusqu'ici, on a manipulé uniquement des événements,

Comment est-ce qu'on affiche la liste des cartes *click* cadeaux ?
--
