== Nouveau besoin

[.notes]
--
Là on est tranquille à faire notre application en event sourcing et CQRS alors que ça marcherait très bien en
Create, Read, Update, Delete standard, je veux dire, on avait toutes les cartes en mains dès le départ,
ça aurait été pénible mais faisable.

Et hop, un Product Manager débarque avec un nouveau besoin.
--

=== "Statistiques des dépenses par semaine"

[cols="3*", options="header"]
|============================================
| barcode | shoppingStore | remainingAmount
| 1234    | Restaurant    | 60 €
|============================================

[.notes]
--
Le pm veut, pour une raison quelconque (c'est un pm), afficher un diagramme des dépenses par jour de la semaine.

Afin de savoir quel est le jour où les utilisateurs dépensent le plus d'argent,
sans doute pour savoir quel est le jour le plus optimisé pour envoyer un rappel.
--

=== Si on n'était pas en event sourcing ?

[.notes]
--
Comme on l'a dit plus tôt, la gestion "standard" est basiquement une perte d'information.

Et que ça, ça arrive souvent, on mitige le risque en disant "bah on a les stats à partir de ma mise en prod"

> Imaginez que vous puissiez répondre à ce besoin avec tout l'historique des données.
--

=== Faisable en event sourcing ?

[.notes]
--
... bah on a les données \^_^
--
