== Prendre des décisions en Event Sourcing

[.notes]
--
- Effectivement, une commande n'est pas toujours applicable.
- Comment peut-on prendre la décision d'appliquer ou non la commande en Event Sourcing ?
--

=== Focus sur la commande de paiement

[source, java, highlight]
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..12,32']

    // Et si le paiement est supérieur au montant restant ?

include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='37..42,51..53']
----

[.notes]
--
Si on reprend la commande de paiement, il faudrait, avant d'accepter la paiement, vérifier si le solde de la carte est suffisant.
--

=== `new GiftCard()`

[source, java, highlight]
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..12,19']
    // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='21']
----

[.notes]
--
- Pour rappel, on instancie notre agrégat uniquement avec l'historique des évènements passés.
- C'est ce qu'on appelle *l'hydratation de l'agrégat*.
- Comment peut-on prendre une décision à partir des évènements ? En les parcourant un à un à chaque fois ?
--

=== Encore une projection

[source, java, highlight='4|7']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..14,19..21']
----

[.notes]
--
- On va plutôt à nouveau utiliser une projection.
- Mais une projection particulière, dynamique, et en mémoire uniquement, appelée "projection de décision".
--

=== `DecisionProjection`

[source, java, highlight='4..8|7|5..6']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..12,67..71']
----

[.notes]
--
- Cette projection est interne à l'agrégat, et non visible depuis l'extérieur. C'est un détail d'implémentation de l'agrégat
- *click*
- Elle ne contient strictement que les données nécessaires à la prise de décision,
- *click*
- ou à l'émission de nouveaux évènements.
--

=== `DecisionProjection.from()`

[source, java, highlight='1|4..7,15|2,8..12|13']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='72..87']
----

[.notes]
--
- On l'initialise à partir de l'historique des évènements passés.
*click*
- Pour cela on va faire une réduction, ou *fold*, de l'historique des évènements.
*click*
- avec comme point de départ le début de l'histoire de la carte cadeau.
*click*
- et une fonction d'accumulation...
--

=== `DecisionProjection.accumulator()`

[source, java, highlight='2..3|5|7|8..10|11']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='101..116']
----

[.notes]
--
- ...qui va appliquer chaque évènement à l'état courant de la projection.
- *click*
- toujours avec du pattern matching, pour être sûr de traiter tout futur type d'évènement,
- *click*
- et de manière similaire au calcul de la projection de lecture
*click*
- avec une subtilité sur la mise à jour le dernier numéro de séquence utilisé
--

=== Utilisation de la projection de décision

[source, java, highlight='..|5..7|15..17|16']
----
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='10..12']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='32..35, 37']
      // ...
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='42, 51..53']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[lines='58..61']
include::../../../src/main/java/io/craft/giftcard/giftcard/domain/GiftCard.java[tags='closingBrace']
----

[.notes]
--
On peut alors se servir de cette projection pour prendre la décision d'appliquer ou non la commande.
--
